default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: app_user
  password: app_password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: app_production
