version: "3"
services:
  db:
    build:
      context: .
      dockerfile: .docker/db/Dockerfile
    volumes:
      - postgres-data:/var/lib/postgresql/data:delegated
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: app_development
  api:
    build:
      context: .
      dockerfile: .docker/api/Dockerfile
    command: /bin/sh -c "rm -f /api/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/api:cached
      - bundle_cache:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: app_development
      POSTGRES_HOST: db
      POSTGRES_TEST_DB: app_test

volumes:
  postgres-data:
  bundle_cache:

