source 'https://rubygems.org'

gem 'rails', '7.1.4.1'

gem "bootsnap", require: false
gem "puma", ">= 5.0"
gem 'pg'
gem 'rack-cors'
gem 'devise'

group :development, :test do
  gem "rspec-rails"
  gem "factory_bot_rails"
end
